name: Compile StyLua
permissions:
  contents: write

on:
  - workflow_dispatch

jobs:
  build:
    name: Convert StyLua to Luau
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Install Rust and Binaryen (wasm-opt)
        run: |
          rustup update stable
          rustup target add wasm32-unknown-unknown
          sudo apt update && sudo apt install -y binaryen

      - name: Build StyLua to WASM
        run: |
          cargo build --release --target wasm32-unknown-unknown

      - name: Run wasm-opt
        run: |
          cd target/wasm32-unknown-unknown/release/
          wasm-opt -O4 stylua_wasynth.wasm -o stylua_wasynth-opt.wasm

      - name: Install Wasynth (wasm2luau)
        run: |
          cargo install --git https://github.com/Rerumu/Wasynth codegen-luau

      - name: Convert WASM to Luau
        run: |
          wasm2luau target/wasm32-unknown-unknown/release/stylua_wasynth-opt.wasm > plugin/src/format/stylua_wasynth.luau

      - name: Commit and Push Changes
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git add plugin/src/format/stylua_wasynth.luau
          git commit -m "feat: Update stylua_wasynth.luau"
          git push
